# Generated by Django 4.0.3 on 2022-03-31 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doawdip', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Reminder',
        ),
    ]
