# Generated by Django 4.0.3 on 2022-03-31 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doawdip', '0003_reminder_completed_reminder_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='body',
            new_name='description',
        ),
    ]
