# Generated by Django 4.0.3 on 2022-04-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doawdip', '0004_rename_body_reminder_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
