# Generated by Django 4.0.3 on 2022-04-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doawdip', '0005_reminder_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
